#!/usr/bin/env sh

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
yarn add -D tailwindcss postcss-cli autoprefixer postcss-import postcss-nesting @fullhuman/postcss-purgecss
cp $dir/config/postcss.config.js .
cp $dir/config/tailwind.config.js .
